-- Migrate data and Drop link between request and component
-- INSERT INTO dbo.Gate_RequestOrder
-- (
    -- MaterialRequestId,
    -- OrderId
-- )
-- SELECT	
-- gmr.MaterialRequestId,
-- gcr.ComponentId
-- FROM dbo.GATE_MaterialRequest gmr
-- INNER JOIN dbo.GATE_ComponentRequest gcr ON gcr.MaterialRequestId = gmr.MaterialRequestId

-- ALTER TABLE dbo.GATE_ComponentRequest
-- DROP CONSTRAINT FK_GATE_ComponentRequest_GATE_MaterialsRequest

-- ALTER TABLE dbo.Gate_RequestOrder ADD CONSTRAINT
-- FK_Gate_RequestOrder_GATE_ComponentRequest FOREIGN KEY
-- (
	-- OrderId
-- ) REFERENCES dbo.GATE_ComponentRequest
-- (
	-- ComponentId
-- ) ON UPDATE  NO ACTION ON DELETE  NO ACTION 
